### ISSUE TITLE
Eroare multipla la orase job

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers_canghelet#11]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/3ss/index.html
Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:

Deschide URL in browser
Apasa RUN SCRAPER

EXPECTED RESULTS:
la toate joburile apar orașe din România

ACTUAL RESULTS:
apare eroarea "BraÈov is not a city in Romania,Targu MureÈ is not a city in Romania,Cluj-Napoca"

![image](https://github.com/peviitor-ro/Scrapers_canghelet/assets/149939147/b3a674e8-3152-47b2-8b87-9eaa3ca2bd26)

**Comment by canghelet** [comment]
Cities have been updated.
![3ss](https://github.com/peviitor-ro/Scrapers_canghelet/assets/114759964/0bdb7651-1ae6-4505-b87e-387335edbfb0)
