### ISSUE TITLE
Pe careers apare un job in romania, dar pe scrapers apar 0 job-uri la run scraper - firma Hogarth

### ISSUE THREAD

**Issue by DianaDascalu2** [peviitor-ro/Scrapers_canghelet#13]
ENVIROMENT: production
COMPANY: Hogarth
URL: https://www.hogarth.com/job/senior-account-manager-3
Official Web Site: https://www.hogarth.com/job/senior-account-manager-3
Browser: Google Chrome
Device: laptop
OS: Windows 10

Precondition:
The [site](https://firme.peviitor.ro/) must be open in browser.

Steps:
1. Click on careers link
2. No job for Romania appear on scrapers.peviitor.ro
3. Pe site-ul firmei Hogarth este cel putin un job in Romania, Bucuresti

Expected result:
Ar fi trebuit sa apara cel putin un job in scraper.

Actual result:
Numar job-uri: 0
![Screenshot 2023-11-23 182243](https://github.com/peviitor-ro/Scrapers-UI/assets/118655267/d221826d-e192-485c-9cbc-cb7013477a08)

**Comment by lalalaurentiu** [comment]
Scraper doesn't work.

**Comment by canghelet** [comment]
scraper was updated. 
![hogarth pe viitor ro](https://github.com/peviitor-ro/Scrapers_canghelet/assets/114759964/7030a57d-f1cd-46ad-a542-96d30c1e2aff)
![hogarth screpers ui](https://github.com/peviitor-ro/Scrapers_canghelet/assets/114759964/079c2512-89d9-489d-b51a-220863264c0a)
