### ISSUE TITLE
Posturile nu corespund la firma Vass

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers_canghelet#15]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/vass/index.html
Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:
Deschide URL in browser
Click pe See Jobs

EXPECTED RESULTS:
Numarul de posturi ar trebui sa corespunda

ACTUAL RESULTS:
In scraper apar 7 joburi iar pe site 0

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/149939147/01bc452c-727d-464d-80f3-64113c524205)

![image](https://github.com/peviitor-ro/Scrapers-UI/assets/149939147/83d32a3a-e0f1-435f-9573-da9289831bd0)

**Comment by canghelet** [comment]
Company name has been updated as requested. 
![scrapers-ui](https://github.com/peviitor-ro/Scrapers_canghelet/assets/114759964/336bf1f4-67db-4ca0-804b-6a089cfbe7b4)
![joburi pe viitor](https://github.com/peviitor-ro/Scrapers_canghelet/assets/114759964/117dbe00-4df9-4c70-8012-adcc77d42807)
