### ISSUE TITLE
Eroare multiplă la oraș job (Release Manager și Associate Marketing Manager) 

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers_canghelet#2]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/sugarcrm/index.html
Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:

Deschide URL in browser
Apasa RUN SCRAPER

EXPECTED RESULTS:
la joburile Release Manager (1592) și Associate Marketing Manager (1595) apar orașe din România

ACTUAL RESULTS:
apare eroarea "Romania - Home Based is not a city in Romania"

![Captură de ecran 2023-11-10 095553](https://github.com/peviitor-ro/Scrapers_canghelet/assets/149939147/9fb67e42-6a63-4c0a-be97-14b996cef359)

**Comment by canghelet** [comment]
Cities have been updated.
![sugar_crm](https://github.com/peviitor-ro/Scrapers_canghelet/assets/114759964/5f9f13c1-740d-4ca2-b65b-2b5959b6d037)
