### ISSUE TITLE
Eroare multiplă la oraș job

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers_canghelet#3]
NVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/neweratechnology/index.html
Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:

Deschide URL in browser
Apasa RUN SCRAPER

EXPECTED RESULTS:
la toate joburile apar orașe din România

ACTUAL RESULTS:
apare eroarea "Romania - Home Based is not a city in Romania", Bucharest, "Romania is not a city in Romania"

![image](https://github.com/peviitor-ro/Scrapers_canghelet/assets/149939147/62b5d408-c63c-479c-a4d6-19f3e33a249a)

**Comment by canghelet** [comment]
Cities have been updated.
![new era technology](https://github.com/peviitor-ro/Scrapers_canghelet/assets/114759964/73da20d5-e126-4569-8221-b6650ed50f2c)
