### ISSUE TITLE
nu rulează scraperul

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers_canghelet#4]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/onapsis/index.html
Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:

Deschide URL in browser
Apasa RUN SCRAPER

EXPECTED RESULTS:
se ruleaza scraperul

ACTUAL RESULTS:
apare eroarea "python3: can't open file 'chainiq_scraper.py': [Errno 2] No such file or directory" si "Status inactiv"

![image](https://github.com/peviitor-ro/Scrapers_canghelet/assets/149939147/4268833d-1286-43f0-a458-b4961c597d4a)

**Comment by davidmondoc** [comment]
rezolvat. asteptam aprobarea modificarilor. te rog verifica maine sau luni
