### ISSUE TITLE
Eroare multiplă la orașe job

### ISSUE THREAD

**Issue by Luizalien** [peviitor-ro/Scrapers_canghelet#7]
ENVIRONMENT: production
URL: https://scrapers.peviitor.ro/src/urban/index.html#
Browser: Chrome
Device: Laptop
OS: Windows

STEPS TO REPRODUCE:

Deschide URL in browser
Apasa RUN SCRAPER

EXPECTED RESULTS:
la toate joburile apar orașe din România

ACTUAL RESULTS:
apare eroarea "Timisoara, Bucuresti is not a city in Romania", "Remote is not a city in Romania"

![image](https://github.com/peviitor-ro/Scrapers_canghelet/assets/149939147/95bc8ddf-8aeb-46be-b134-5fc2b19de788)

**Comment by canghelet** [comment]
Scraper has been updated.
![urban](https://github.com/peviitor-ro/Scrapers_canghelet/assets/114759964/3f27f404-7eee-42bf-9ef4-3dc4c5735818)
